# Generated by Django 4.2.30 on 2026-04-23 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0001_initial'),
        ('environments', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('assertions', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='apis.apidefinition')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcases', to='environments.environment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='projects.project')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
