# Generated by Django 4.2.30 on 2026-04-24 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('environments', '0001_initial'),
        ('apis', '0001_initial'),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='default_environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_testcases', to='environments.environment'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('request_overrides', models.JSONField(blank=True, default=dict)),
                ('extract_rules', models.JSONField(blank=True, default=list)),
                ('assertion_rules', models.JSONField(blank=True, default=list)),
                ('continue_on_failure', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teststeps', to='apis.apidefinition')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teststeps', to='environments.environment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teststeps', to='projects.project')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='testcases.testcase')),
            ],
            options={
                'ordering': ['testcase_id', 'order', 'id'],
                'unique_together': {('testcase', 'order')},
            },
        ),
    ]
