# Generated by Django 4.2.30 on 2026-04-23 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('body_template', models.JSONField(blank=True, default=dict)),
                ('expected_result', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='projects.project')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
