# Generated by Django 4.2.30 on 2026-04-24 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_testcase_default_environment_testcase_description_and_more'),
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='testcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='testcases.testcase'),
        ),
        migrations.CreateModel(
            name='ExecutionStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('extracted_variables', models.JSONField(blank=True, default=dict)),
                ('assertion_result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='executions.testexecution')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='testcases.testcase')),
                ('teststep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_results', to='testcases.teststep')),
            ],
            options={
                'ordering': ['execution_id', 'order', 'id'],
            },
        ),
    ]
